[versions]
androidGradlePlugin = "8.8.0-alpha04"
kotlin = "1.9.22"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
